# Generated by Django 3.2.8 on 2021-10-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='John Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
